### ISSUE TITLE
[FEATURE] UNDO and REDO

### ISSUE THREAD

**Issue by Andreas-Coding** [DarkKronicle/AdvancedChatCore#11]
**Is your feature request related to a problem? Please describe.**
Whenever you type stuff in the Minecraft chat window, you might want to reverse your doings, correct misspellings, reorganize your thoughts and various other things. But in its unedited state, once you've removed text from what you were about to type, its gone and you'll need to retype it. 

**Describe the solution you'd like**
The chat input keeps track of what you type and makes actions reversible. It therefor reacts on the common hotkeys for undo (`CTRL + z`) and redo (`CTRL + SHIFT + z`).

**Comment by DarkKronicle** [comment]
Will be added in 1.3.0
