### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ilmangoi** [DarkKronicle/AdvancedChatCore#13]
It conflicts with the latest version of Tweakeroo.
When I press T to open the chat bar, my game collapsed.

 Crash Report: https://pastebin.com/UHWMe9hE

**Comment by DarkKronicle** [comment]
This is resolved by disabling persistent chat in Tweakeroo. This setting can be enabled in AdvancedChat settings

**Comment by UltraBlackLinux** [comment]
Ah yes. Thanks for calling this issue "[BUG]"
