### ISSUE TITLE
[BUG] filter profanity filters some regular words

### ISSUE THREAD

**Issue by RyanCR03** [DarkKronicle/AdvancedChatCore#15]
**Describe the bug**
When using the filter profanity, it will filter some words that have them in it. (e.g. assume - ***ume)

**Minecraft Info**
AdvancedChatBox-1.1.2

**To Reproduce**
1. Turn on the filter profanity option
2. Send a message like assume
3. first 3 letters are censored 

**Expected behavior**
It wouldn't censor any profanity in words that pass the spellchecker

**Screenshots**
![image](https://user-images.githubusercontent.com/32957560/147950735-c13cd29a-767c-46ff-a333-fad4dd892560.png)

**Comment by DarkKronicle** [comment]
I think I figured out a way to help minimize this. I’m planning on making profanity filter a lot cooler in the future.

**Comment by DarkKronicle** [comment]
Added!
