### ISSUE TITLE
[BUG] "Update Stacked Messages" setting reversed (?)

### ISSUE THREAD

**Issue by LeaPhant** [DarkKronicle/AdvancedChatCore#16]
**Describe the bug**
Not directly a bug, but the "Update Stacked Messages" setting does the reverse of what's expected. Setting it to `true` sends a new message, while `false` updates the old one. It's already been like this in the old AdvancedChat so it's not a new thing but I've always felt like it was confusing – maybe it should be worded differently.

**Minecraft Info**
Minecraft information:
- AdvancedChatCore 1.3.2-1.18

**Comment by DarkKronicle** [comment]
Will be reworded next update
