### ISSUE TITLE
[FEATURE] Upload to modrinth and/or update old modrinth page

### ISSUE THREAD

**Issue by solonovamax** [DarkKronicle/AdvancedChatCore#17]
**Is your feature request related to a problem? Please describe.**
Currently, the [old modrinth page](https://www.modrinth.com/mod/advancedchat) only has versions up to 1.16.5. This is confusing for anyone searching for it on modrinth

**Describe the solution you'd like**
It would be nice if the new versions could be uploaded on modrinth.

**Comment by DarkKronicle** [comment]
Added now
