### ISSUE TITLE
[FEATURE] Copy text in chat

### ISSUE THREAD

**Issue by metalcupcake5** [DarkKronicle/AdvancedChatCore#18]
**Is your feature request related to a problem? Please describe.**
Occasionally I would like to directly quote a message in chat, however it is tedious to type out the entire message manually, especially if it is long.

**Describe the solution you'd like**
A keybind and/or toggle for the ability to copy messages in chat(ex. with right click) to clipboard.

**Comment by DarkKronicle** [comment]
I've been thinking about adding this to either HUD or Log. I'll plan on this for the next update (but no eta atm, sorry. Hopefully not too long).

**Comment by metalcupcake5** [comment]
👍 thanks

**Comment by DarkKronicle** [comment]
It's available in the discord now. Probably published in the next few days.
