### ISSUE TITLE
[BUG] Translation strings aren't being used.

### ISSUE THREAD

**Issue by TNTea** [DarkKronicle/AdvancedChatCore#2]
**Description**
Every text just displays its ID instead of using the localized string.

**Minecraft Info**
Version: 1.17.1
- Fabric Loader 0.11.6
- Fabric API 0.37.2+1.17
- MaLiLib 0.10.0-dev.24
- Architectury 2.3.24
- Mod Menu 2.0.4
- Sodium 0.3.0+build.5
- Lithium 0.7.3
- Borderless Mining 1.0.6
- MiniHUD 0.19.0
- Roughly Enough Items 6.0.267-alpha
- VoxelMap 1.10.15
- Litematica 0.0.0-dev.20210713.103711
- Command Macros 1.5.2-1.17

- **AdvancedChatCore 1.0.1-1.17.1 (beta5)**

**To Reproduce**

1. Join a World.
2. Open the AC Config (via Mod Menu)
3. Enjoy.

**Expected behavior**
The Text should use the strings from the en_us.json

**Screenshots**
![image](https://user-images.githubusercontent.com/43808589/129449229-c8c9ac51-227a-44a6-b556-27f9e467bd1a.png)

**Comment by DarkKronicle** [comment]
Hmm that's really weird. All the lang stuff is setup. I'll try to figure out why it doesn't use it.

**Comment by DarkKronicle** [comment]
Omg IntelliJ decided to not have the `.` make a new folder 👀  
![image](https://user-images.githubusercontent.com/38167691/129453080-0843f0ac-944e-4a95-a82f-7c9b9f0676cf.png)
Fixed now. Thanks!
