### ISSUE TITLE
[BUG] 1.18.2 startup crash with AC Filters

### ISSUE THREAD

**Issue by UltraBlackLinux** [DarkKronicle/AdvancedChatCore#37]
**Describe the bug**
1.18.2 Crashes with an error

**Minecraft Info**
Minecraft information:
- AdvancedChat version: AC 1.4.2

**To Reproduce**
Start the game 

EDIT: With advanced chat FILTERS installed

**Expected behavior**

**Additional context**
```
LinkageError: loader constraint violation: when resolving method
'org.slf4j.Logger com.mojang.logging.LogUtils.getLogger()' the class loader
net.fabricmc.loader.impl.launch.knot.KnotClassLoader @536dbea0 of the current class, net/minecraft/client/main/Main, and
the class loader 'app' for the
method's defining class, com/mojang/logging/LogUtils, have different Class objects for the type org/slf4j/Logger used in the signature (net.minecraft.client.main.Main is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @536dbea0, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @3f1d2e23; com.mojang.logging.LogUtils is in unnamed module of loader 'app')
```

**Comment by Boobies** [comment]
This isn't a bug, AC has not been ported to 1.18.2 so it's not really useful to post this.

**Comment by UltraBlackLinux** [comment]
I assumed that this was supposed to work on 1.18.2 ootb

**Comment by vacla** [comment]
@UltraBlackLinux as you know malilib isnt updated, this one wouldnt work either

**Comment by UltraBlackLinux** [comment]
> @UltraBlackLinux as you know malilib isnt updated, this one wouldnt work either

It now is

**Comment by DarkKronicle** [comment]
Been super busy. I’ll hopefully get around to updating soon.

**Comment by DarkKronicle** [comment]
Fixed now
