### ISSUE TITLE
[BUG] Empty lines get stripped

### ISSUE THREAD

**Issue by MrKinau** [DarkKronicle/AdvancedChatCore#38]
**Describe the bug**
Empty messages are not displayed in the chat windows as in vanilla.

**Minecraft Info**
- AdvancedChatCore-1.18.2-1.4.4
- AdvancedChatHub-1.18.2-1.2.3

**To Reproduce**
1. Send an empty message (e.g. `/tellraw @a {"text":""}`)
2. Don't see an empty line in the chat window

**Expected behavior**
You should see an empty line in the chat window.

**Screenshots**

Vanilla:
![image](https://user-images.githubusercontent.com/13185260/158425436-0f36a588-5c19-4427-8bf0-485ac612a209.png)

Using AdvancedChat:
![image](https://user-images.githubusercontent.com/13185260/158425767-1cf4fb0e-db96-496e-8432-ef4c17a62a2f.png)

**Additional context**
After adding a filter, which is designed to bypass this issue `^$` replaced with something and the message is triggered I get this exception: https://pastebin.com/Sbnh296C and the game crashes if you want to edit the filter again.

**Comment by DarkKronicle** [comment]
Fixed in next update
