### ISSUE TITLE
[FEATURE] Some way of getting to the configs without mod menu.

### ISSUE THREAD

**Issue by TNTea** [DarkKronicle/AdvancedChatCore#4]
Currently the AdvancedChatCore doesn't provide a way to get to the configuration page without Mod Menu, as the "Settings" button isn't part of the baseline anymore. Having to install the GUI Module or Mod Menu feels kinda weird.

**Comment by DarkKronicle** [comment]
I'm trying not to mess with chat too much without ACHUD, but maybe a button that you can turn off would work? Do you have any ideas? (Currently there's a debug keybind `Y` for it)

**Comment by TNTea** [comment]
Oh I didn't know that there was a Hotkey for it. That's good enough imo.
Could have looked at the Control settings, sorry. ^^

Is is supposed to be called 'openlog'?
![image](https://user-images.githubusercontent.com/43808589/129455720-44ab70c6-9528-49bb-a74f-73f49dd020e7.png)

**Comment by DarkKronicle** [comment]
Oh yeah I need to change that lol

**Comment by DarkKronicle** [comment]
There is now a button
