### ISSUE TITLE
Good mod but many issues

### ISSUE THREAD

**Issue by yeeterlol** [DarkKronicle/AdvancedChatCore#51]
In my opinion, this is a decent mod which allows you to seperate chat but I have 1 minor issue. 
Way too many crashes, legit even breathing will crash your game because of this mod. 
If there were less crashes then this mod would be perfect but for right now, this issue needs to be fixed.

**Comment by DarkKronicle** [comment]
There's an issue with ACHUD on 1.19.1 that isn't fixed yet.

**Comment by DarkKronicle** [comment]
If you could explain some crashes that would help fix them.

**Comment by Fury-101** [comment]
also, posting a crash log would help

**Comment by gurrrrrrett3** [comment]
crash log would be amazing

**Comment by allinkdev** [comment]
crash log would be exemplary

**Comment by kyrtion** [comment]
crash log would be awesome

**Comment by yeeterlol** [comment]
https://hastebin.com/amowasapes.properties
Crashlog

**Comment by yeeterlol** [comment]
Wait, all the issues I had are already reported.
