### ISSUE TITLE
[BUG] Some characters displayed wrongly

### ISSUE THREAD

**Issue by MrKinau** [DarkKronicle/AdvancedChatCore#54]
**Describe the bug**
Some characters get displayed wrongly. These are some examples, which all get replaced with two Unicode replacement characters
`🍖🪣🔔🔥🌊🛡🗡🏹🪓🔱🎣🧪`

**Minecraft Info**
Minecraft information:
- AdvancedChatHUD version [current main branch 1.19.1-1.3.4]
- AdvancedChatCore version [current main branch 1.19.1-1.5.6]

**To Reproduce**
1. Install HUD and Core and just type one of the above mentioned characters in chat
2. See it being displayed wrongly

**Expected behavior**
The character should be displayed as in the chat typing box.

**Screenshots**
![image](https://user-images.githubusercontent.com/13185260/185833135-645fefd4-670f-46e4-b962-e449833a3396.png)

**Additional context**
I think it's because these characters need 2 bytes in UTF-16. I've tried tracking down the source of this issue, but I couldn't fix it. Before the `shallowClone()` method is called in the HUD, the text seems to be fine, but after that these character are replaced. Seems like the `OrderedText.accept` CharacterVisitor called [here](https://github.com/DarkKronicle/AdvancedChatCore/blob/main/src/main/java/io/github/darkkronicle/advancedchatcore/util/TextBuilder.java#L31), just outputs two [65533 Unicodes](https://unicodeplus.com/U+FFFD), but I don't know why (maybe this isn't the source of the bug and just a side effect idk).

**Comment by allinkdev** [comment]
This is probably related to how the emojis you sent are in reality, 2 characters long. You should double check if the incorrect output are really 65533 Unicode characters. I'm guessing it's outputting Unicode characters that Minecraft can't display.

**Comment by MrKinau** [comment]
I've debugged the codePoint variable at [this method](https://github.com/DarkKronicle/AdvancedChatCore/blob/main/src/main/java/io/github/darkkronicle/advancedchatcore/util/TextBuilder.java#L31) and got 2 times 65533 as a result for the emoji. Seems like the `ChatMessages.breakRenderedChatMessageLines` creates those destroyed `OrderedText` objects, but I don't know why.

**Comment by DarkKronicle** [comment]
Found the issue! `StyleFormatter` broke apart each 'character' (in this case byte). This meant that each byte of a UTF-8 character was treated as different. Will get this updated soon.

**Comment by DarkKronicle** [comment]
Fixed on curseforge now, and I think modrinth

**Comment by MrKinau** [comment]
Thank you ❤️
