### ISSUE TITLE
[BUG] Keeping messages after disconnecting doesn't work.

### ISSUE THREAD

**Issue by TNTea** [DarkKronicle/AdvancedChatCore#6]
**Description**
Setting clearondisconnect to "false" has no effect.

**Minecraft Info**
Version: 1.17.1
- Fabric Loader 0.11.6
- Fabric API 0.37.2+1.17
- MaLiLib 0.10.0-dev.24
- Architectury 2.3.24
- Mod Menu 2.0.4
- Sodium 0.3.0+build.5
- Lithium 0.7.3
- Borderless Mining 1.0.6
- MiniHUD 0.19.0
- Roughly Enough Items 6.0.267-alpha
- VoxelMap 1.10.15
- Litematica 0.0.0-dev.20210713.103711
- Command Macros 1.5.2-1.17

- **AdvancedChatCore 1.0.1-1.17.1 (beta5)**

**To Reproduce**

1. Join a world.
2. Set clearondisconnect to 'false'.
3. Type some messages.
4. Leave the world.
5. Rejoin the same world.

**Expected behavior**
The messages should persist and still be there after rejoining the world.

**Comment by DarkKronicle** [comment]
Currently this is more of an internal setting, but I guess it wouldn't be that hard to implement. I'll try to add it.

**Comment by DarkKronicle** [comment]
Added!
