### ISSUE TITLE
[BUG] Wnen i install AdvanceChat* Mod, can cause crash client

### ISSUE THREAD

**Issue by 8MiYile** [DarkKronicle/AdvancedChatCore#60]
**Describe the bug**
Log Link
[HMCL.Log](https://mclo.gs/rIlg8rc)
[Latest.log](https://mclo.gs/MDW0ZWL)
[Crash-Report](https://mclo.gs/cUl4t0U)

**Minecraft Info**
Minecraft information:
- AdvancedChatBox-1.19.2-1.1.6
- AdvancedChatCore-1.19.3-1.5.9
- AdvancedChatHUD-1.19.3-1.3.7

**To Reproduce**
1. install AdcancedChat*
2. Open Game
3. Crash it

**Expected behavior**

**Screenshots**
None
just HMCL crash tip window

**Additional context**
Add any other context about the problem here. This could be a mods list, server, etc.

**Comment by DarkKronicle** [comment]
So the issue seems to be AdvancedChatBox, but I haven't seen this issue before. It may be a mod conflict. I know meteor client can sometimes do weird stuff.

**Comment by 8MiYile** [comment]
I will submit the same content in the AdvancedChatBox issue
