### ISSUE TITLE
[BUG] Can't put Japanese characters to chat.

### ISSUE THREAD

**Issue by Enderlold** [DarkKronicle/AdvancedChatCore#7]
**Describe the bug**
When using IME, Can't put characters to chat. IME is software to put characters, such as Japanese, Chinese, Korean.
Wikipedia page about IME. https://en.wikipedia.org/wiki/Input_method
By the way I'm bad at English. I'm sorry if my English is difficult to understand.  

**Minecraft Info**
Version: 1.17.1

- Fabric Loader 0.11.6
- fabric api 0.37.2+1.17
- AdvancedChatCore 1.0.1 1.17.1 beta7
- hydrogen 0.3
- lithium 0.7.4
- malilib 0.10.0-dev.24
- modmenu 2.0.4
- smoothboot 1.6.0
- sodium 0.3.2+build.7
- starlight 1.0.0 RC3

**To Reproduce**
1. Open chat
2. Trying to put some Japanese character with IME

**Expected behavior**
There should be put characters.

**Comment by DarkKronicle** [comment]
Hmm interesting. Does this work in vanilla Minecraft?

**Comment by Enderlold** [comment]
Yes, this works on vanilla.

**Comment by Enderlold** [comment]
I completely forgot about this mod. I'm sorry about that.
I tried latest build 1.4.6 (1.18.2), it's been fixed.
I don't know when and which version is the first fixed version but thank you for your hard working.
At least, 1.4.6 (1.18.2) is the fixed version as I know.
I'm closing this issue.

And also about dependency
> malilib 0.12.1 (1.18.2)

**Comment by DarkKronicle** [comment]
Hmm. Good to know
